### ISSUE TITLE
Interceptor doesn't work on apps in a subfolder

### ISSUE THREAD

**Issue by bdw429s** [elpete/SESOnRequest#3]
If there is an appMapping, append it to the URL.

**Comment by bdw429s** [comment]
Fixed in https://github.com/elpete/SESOnRequest/commit/c7b966a849603ded5e69077b9670a4b9daba3a7f

@elpete Please release a new version at your convenience.

**Comment by elpete** [comment]
Released as `1.1.0`.  Thanks!
